export function initNavbar(){document.addEventListener('DOMContentLoaded',()=>{/* navbar init */});}

// navbar.js placeholder section 1
// navbar.js placeholder section 2
// navbar.js placeholder section 3
// navbar.js placeholder section 4
// navbar.js placeholder section 5
// navbar.js placeholder section 6
// navbar.js placeholder section 7
// navbar.js placeholder section 8
// navbar.js placeholder section 9
// navbar.js placeholder section 10
// navbar.js placeholder section 11
// navbar.js placeholder section 12
// navbar.js placeholder section 13
// navbar.js placeholder section 14
// navbar.js placeholder section 15
// navbar.js placeholder section 16
// navbar.js placeholder section 17
// navbar.js placeholder section 18
// navbar.js placeholder section 19
// navbar.js placeholder section 20
// navbar.js placeholder section 21
// navbar.js placeholder section 22
// navbar.js placeholder section 23
// navbar.js placeholder section 24
// navbar.js placeholder section 25
// navbar.js placeholder section 26
// navbar.js placeholder section 27
// navbar.js placeholder section 28
// navbar.js placeholder section 29
// navbar.js placeholder section 30
// navbar.js placeholder section 31
// navbar.js placeholder section 32
// navbar.js placeholder section 33
// navbar.js placeholder section 34
// navbar.js placeholder section 35
// navbar.js placeholder section 36
// navbar.js placeholder section 37
// navbar.js placeholder section 38
// navbar.js placeholder section 39
// navbar.js placeholder section 40
// navbar.js placeholder section 41
// navbar.js placeholder section 42
// navbar.js placeholder section 43
// navbar.js placeholder section 44
// navbar.js placeholder section 45
// navbar.js placeholder section 46
// navbar.js placeholder section 47
// navbar.js placeholder section 48
// navbar.js placeholder section 49
// navbar.js placeholder section 50
// navbar.js placeholder section 51
// navbar.js placeholder section 52
// navbar.js placeholder section 53
// navbar.js placeholder section 54
// navbar.js placeholder section 55
// navbar.js placeholder section 56
// navbar.js placeholder section 57
// navbar.js placeholder section 58
// navbar.js placeholder section 59
// navbar.js placeholder section 60
// navbar.js placeholder section 61
// navbar.js placeholder section 62
// navbar.js placeholder section 63
// navbar.js placeholder section 64
// navbar.js placeholder section 65
// navbar.js placeholder section 66
// navbar.js placeholder section 67
// navbar.js placeholder section 68
// navbar.js placeholder section 69
// navbar.js placeholder section 70
// navbar.js placeholder section 71
// navbar.js placeholder section 72
// navbar.js placeholder section 73
// navbar.js placeholder section 74
// navbar.js placeholder section 75
// navbar.js placeholder section 76
// navbar.js placeholder section 77
// navbar.js placeholder section 78
// navbar.js placeholder section 79
// navbar.js placeholder section 80