export function initStickyHeader(){window.addEventListener('scroll',()=>{/* sticky header */},{passive:true});}

// sticky-header.js placeholder section 1
// sticky-header.js placeholder section 2
// sticky-header.js placeholder section 3
// sticky-header.js placeholder section 4
// sticky-header.js placeholder section 5
// sticky-header.js placeholder section 6
// sticky-header.js placeholder section 7
// sticky-header.js placeholder section 8
// sticky-header.js placeholder section 9
// sticky-header.js placeholder section 10
// sticky-header.js placeholder section 11
// sticky-header.js placeholder section 12
// sticky-header.js placeholder section 13
// sticky-header.js placeholder section 14
// sticky-header.js placeholder section 15
// sticky-header.js placeholder section 16
// sticky-header.js placeholder section 17
// sticky-header.js placeholder section 18
// sticky-header.js placeholder section 19
// sticky-header.js placeholder section 20
// sticky-header.js placeholder section 21
// sticky-header.js placeholder section 22
// sticky-header.js placeholder section 23
// sticky-header.js placeholder section 24
// sticky-header.js placeholder section 25
// sticky-header.js placeholder section 26
// sticky-header.js placeholder section 27
// sticky-header.js placeholder section 28
// sticky-header.js placeholder section 29
// sticky-header.js placeholder section 30
// sticky-header.js placeholder section 31
// sticky-header.js placeholder section 32
// sticky-header.js placeholder section 33
// sticky-header.js placeholder section 34
// sticky-header.js placeholder section 35
// sticky-header.js placeholder section 36
// sticky-header.js placeholder section 37
// sticky-header.js placeholder section 38
// sticky-header.js placeholder section 39
// sticky-header.js placeholder section 40
// sticky-header.js placeholder section 41
// sticky-header.js placeholder section 42
// sticky-header.js placeholder section 43
// sticky-header.js placeholder section 44
// sticky-header.js placeholder section 45
// sticky-header.js placeholder section 46
// sticky-header.js placeholder section 47
// sticky-header.js placeholder section 48
// sticky-header.js placeholder section 49
// sticky-header.js placeholder section 50
// sticky-header.js placeholder section 51
// sticky-header.js placeholder section 52
// sticky-header.js placeholder section 53
// sticky-header.js placeholder section 54
// sticky-header.js placeholder section 55
// sticky-header.js placeholder section 56
// sticky-header.js placeholder section 57
// sticky-header.js placeholder section 58
// sticky-header.js placeholder section 59
// sticky-header.js placeholder section 60
// sticky-header.js placeholder section 61
// sticky-header.js placeholder section 62
// sticky-header.js placeholder section 63
// sticky-header.js placeholder section 64
// sticky-header.js placeholder section 65
// sticky-header.js placeholder section 66
// sticky-header.js placeholder section 67
// sticky-header.js placeholder section 68
// sticky-header.js placeholder section 69
// sticky-header.js placeholder section 70
// sticky-header.js placeholder section 71
// sticky-header.js placeholder section 72
// sticky-header.js placeholder section 73
// sticky-header.js placeholder section 74
// sticky-header.js placeholder section 75
// sticky-header.js placeholder section 76
// sticky-header.js placeholder section 77
// sticky-header.js placeholder section 78
// sticky-header.js placeholder section 79
// sticky-header.js placeholder section 80